version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app  # Монтирование для локальной разработки
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
