name: CI/CD Pipeline

on:
  push:
    branches:
      - new-feature  # Ветка для автоматического запуска
  workflow_dispatch:  # Возможность ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: atillaaa/retreet_bot_narayana:new-feature  # Замените на ваш Docker Hub репозиторий

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production  # Укажите окружение

    steps:
      - name: Start SSH agent and add deploy key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_DEPLOY }}

      - name: List SSH identities
        run: ssh-add -l

      - name: Test SSH connection to server
        run: ssh -o StrictHostKeyChecking=no root@92.255.78.196 "echo 'SSH connection works!'"

      - name: Configure GitHub SSH on server
        run: |
          ssh -o StrictHostKeyChecking=no root@92.255.78.196 bash -c "
          mkdir -p ~/.ssh &&
          echo '${{ secrets.GITHUB_SSH_KEY }}' | tr -d '\r' > ~/.ssh/id_rsa_github &&
          chmod 600 ~/.ssh/id_rsa_github &&
          ssh-keyscan github.com >> ~/.ssh/known_hosts &&
          echo 'Host github.com\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_rsa_github\n  IdentitiesOnly yes' > ~/.ssh/config &&
          chmod 600 ~/.ssh/config
          "

      - name: Test GitHub SSH access from server
        run: ssh -o StrictHostKeyChecking=no root@92.255.78.196 "ssh -T git@github.com || echo 'GitHub SSH test failed.'"

      - name: Clone repository if not exists
        run: |
          ssh -o StrictHostKeyChecking=no root@92.255.78.196 bash -c "
          if [ ! -d /home/root/project_root/.git ]; then
            git clone git@github.com:Ali-Kizilbash/retreet_bot_narayana.git /home/root/project_root
          fi
          "

      - name: Pull latest changes
        run: ssh -o StrictHostKeyChecking=no root@92.255.78.196 "cd /home/root/project_root && git pull origin new-feature"

      - name: Check Docker status
        run: ssh -o StrictHostKeyChecking=no root@92.255.78.196 "docker ps -a"

      - name: Restart Docker containers
        run: |
          ssh -o StrictHostKeyChecking=no root@92.255.78.196 bash -c "
          cd /home/root/project_root &&
          docker-compose down &&
          docker-compose up -d
          "

      - name: Verify deployment
        run: ssh -o StrictHostKeyChecking=no root@92.255.78.196 "echo 'Deployment verification complete.'"
