name: CI/CD Pipeline

on:
  push:
    branches:
      - new-feature  # Ваши ветки для пуша
  workflow_dispatch:  # Добавлено для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: atillaaa/retreet_bot_narayana:new-feature  # Замените на ваш Docker Hub репозиторий

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # Проверка содержимого SSH-агента
      - name: List SSH identities
        run: ssh-add -l

      # Проверка доступа к серверу
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no root@92.255.78.196 "echo 'SSH connection works!'"

      # Проверка доступности GitHub из сервера
      - name: Test GitHub SSH access from server
        run: |
          ssh -o StrictHostKeyChecking=no root@92.255.78.196 "ssh -T git@github.com"

      # Проверка существования директории
      - name: Check project directory on server
        run: |
          ssh -o StrictHostKeyChecking=no root@92.255.78.196 "if [ -d /home/root/project_root ]; then echo 'Directory exists'; else echo 'Directory does not exist'; fi"

      # Проверка содержимого директории
      - name: List files in project directory
        run: |
          ssh -o StrictHostKeyChecking=no root@92.255.78.196 "ls -la /home/root/project_root"

      # Логгирование вывода команды `git pull`
      - name: Pull changes from GitHub
        run: |
          ssh -o StrictHostKeyChecking=no root@92.255.78.196 "cd /home/root/project_root && git pull origin new-feature"

      # Проверка текущего состояния Docker
      - name: Check Docker status
        run: |
          ssh -o StrictHostKeyChecking=no root@92.255.78.196 "docker ps -a"

      # Перезапуск контейнеров с логами
      - name: Restart containers with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no root@92.255.78.196 "cd /home/root/project_root && docker-compose down && docker-compose up -d && docker-compose logs"

